//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PpcLocal.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public long ClienteID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    }
}
